### ISSUE TITLE
Specifying Jasmine as the default test framework?

### ISSUE THREAD

**Issue by kokujin** [speckjs/speckjs#165]
How can I specify Jasmine to be the default test framework instead of Tape? I am using the Atom editor plugin. Thanks

**Comment by gregRV** [comment]
Hey @kokujin, thanks for asking. Here's what you'll want to do for Jasmine tests:
1. Open Atom's Settings
2. Select `Packages` tab
   ![image](https://cloud.githubusercontent.com/assets/3118710/11938198/f1fe03aa-a7cd-11e5-94a7-17eb9f43e3d2.png)
3. Since you already have SpeckJS installed, you should see `speckjs` under Community Packages.
   ![image](https://cloud.githubusercontent.com/assets/3118710/11938190/e3169258-a7cd-11e5-8e3d-b714b7e1c1fd.png)
4. Click `Settings` in the `speckjs` package
5. Enter `jasmine` in the `Test Framework` field
   ![image](https://cloud.githubusercontent.com/assets/3118710/11938239/53c694f8-a7ce-11e5-9bcd-ef35eef010ae.png)

You're all set! Now Jasmine tests will be created when you run `Speckjs: Build` (accessible through the Command Palette, as well as the hot key `ctrl + alt + s`)!

![atomjasmine](https://cloud.githubusercontent.com/assets/3118710/11938133/6eaa52a6-a7cd-11e5-8114-16b9c64bca81.gif)

Hope this helps!

**Comment by kokujin** [comment]
Hi @gregRV , this helps a lot, its a pity that its not documented on the site.

I am getting errors though

```
Error: Cannot find module '/home/kokujin/development/research/speck_test/spec/support/jasmine.json'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Jasmine.loadConfigFile (/home/kokujin/development/research/speck_test/node_modules/jasmine/lib/jasmine.js:83:16)
    at runJasmine (/home/kokujin/development/research/speck_test/node_modules/jasmine/lib/command.js:92:11)
    at Command.run (/home/kokujin/development/research/speck_test/node_modules/jasmine/lib/command.js:49:7)
    at Object.<anonymous> (/home/kokujin/development/research/speck_test/node_modules/jasmine/bin/jasmine.js:11:9)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
npm ERR! Test failed.  See above for more details.
```

**Comment by kokujin** [comment]
ok, got it to work. You really have to mention that the test frameworks have to be installed and configured in the docs. I expected them to be pulled as dependencies.

**Comment by gregRV** [comment]
Thanks for the feedback, @kokujin. We'll definitely take another look at the documentation soon.
